import { Component, OnInit } from '@angular/core';
import { Observable, of } from 'rxjs';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent implements OnInit {
  title = 'mercer-components-test';
  data: any = null;
  value: any = null;
  items = new Array(15);

  ngOnInit(): void {
    this.getData().subscribe((response) => {
      console.log('response', response);
      this.data = response;
    });
  }

  ngAfterViewInit(): void {}

  getData(): Observable<unknown> {
    return of({
      mappings: [
        {
          accuracy: 0.8,
          attributeDefinition:
            'Unique employee identifier, without dashes or other formatting. Exclude government identification numbers and personal information.\nChina: Please leave employee identifier blank when filling in employee data of China Mainland companies, Mercer Data Connector will automatically assign employee identifier after you upload employee data. If the company submitted data last year, employee identifiers have been assigned in the employee data template which you can download on this page. You can continue to use these assigned employee identifiers to fill in employee data.',
          attributeType: 'String',
          isRequired: true,
          sectionName: 'Employee',
          sampleValue: [
            '00001688',
            '00029113',
            '00066127',
            '00075915',
            '00087016',
            '00165302',
            '00184905',
            '00196421',
            '00227707',
            '00228210',
            '00234802',
            '00236307',
          ],
          target: 'employee_id',
        },
        {
          accuracy: 0.8,
          attributeDefinition:
            'Year Of Birth Without dashes or other formatting.',
          attributeType: 'String',
          isRequired: false,
          sectionName: 'Employee',
          sampleValue: [
            '1956',
            '1955',
            '1964',
            '1986',
            '1961',
            '1958',
            '1964',
            '1979',
            '1977',
            '1967',
            '1994',
          ],
          target: 'birth_year',
        },
        {
          accuracy: 0.8,
          attributeDefinition: 'Commencement year of employment',
          attributeType: 'String',
          isRequired: false,
          sectionName: 'Employee',
          sampleValue: [
            '1997',
            '2002',
            '2005',
            '2006',
            '2007',
            '2013',
            '2014',
            '2015',
            '2016',
            '2017',
            '2018',
            '2019',
          ],
          target: 'hire_year',
        },
        {
          accuracy: 0.8,
          attributeDefinition:
            "Gender of the employee, reflecting the individual's identification as male, female, or another gender identity.",
          attributeType: 'String',
          isRequired: false,
          sectionName: 'Employee',
          sampleValue: ['Female', 'Male', 'Non-Binary'],
          target: 'gender',
        },
        {
          accuracy: 0.8,
          attributeDefinition:
            "Please indicate the employee's workplace model, e.g. on-site/office, hybrid or remote. Hybrid means a regular, flexible part-time on-site/in the office and part-time remotely.",
          attributeType: 'String',
          isRequired: false,
          sectionName: 'Employee',
          sampleValue: [
            'Full-Time',
            'On-Site/In the Office',
            'Hybrid',
            'Full-Time Remote',
          ],
          target: 'workplace_model',
        },
        {
          accuracy: 0.8,
          attributeDefinition:
            'Three letter codes as per international standard (ISO 4217) which is established as norm in banking and business all over the world for defining different currencies (e.g., USD, EUR, CNY) and applicable for compensation data (except data under LTI plan).',
          attributeType: 'string',
          isRequired: true,
          sectionName: 'Employee',
          sampleValue: [
            'Australian Dollar (AUD)',
            'Euro (EUR)',
            'United States Dollar (USD)',
            'Albanian Lek (ALL)',
            'Algerian Dinar (DZD)',
            'Angolan Kwanza (AOA)',
            'Argentine Peso (ARS)',
            'Armenian Dram (AMD)',
            'Azerbaijan New Manat (AZN)',
            'Bahraini Dinar (BHD)',
            'Bangladeshi Taka (BDT)',
            'Belarusian Ruble (BYN)',
            'Bolivian Boliviano (BOB)',
            'Bosnia and Herzegovina Convertible Mark (BAM)',
            'Botswana Pula (BWP)',
            'Brazilian Real (BRL)',
            'British Pound (GBP)',
            'Brunei Dollar (BND)',
            'Bulgarian Lev (BGN)',
            'Burmese Kyat (MMK)',
            'Burundian Franc (BIF)',
            'Cambodian Riel (KHR)',
            'Canadian Dollar (CAD)',
            'Central African CFA Franc (XAF)',
            'Chilean Peso (CLP)',
            'Chinese Yuan (CNY)',
            'Colombian Peso (COP)',
            'Congolese Franc (CDF)',
            'Costa Rican Colon (CRC)',
            'Czech Koruna (CZK)',
            'Danish Krone (DKK)',
            'Dominican Republic Peso (DOP)',
            'Egyptian Pound (EGP)',
            'Ethiopian Birr (ETB)',
            'Georgian Lari (GEL)',
            'Ghanaian Cedi (GHS)',
            'Guatemalan Quetzal (GTQ)',
            'Guinean Franc (GNF)',
            'Honduran Lempira (HNL)',
            'Hong Kong Dollar (HKD)',
            'Hungarian Forint (HUF)',
            'Indian Rupee (INR)',
            'Indonesian Rupiah (IDR)',
            'Iranian Rial (IRR)',
            'Iraqi Dinar (IQD)',
            'Israeli New Shekel (ILS)',
            'Jamaican Dollar (JMD)',
            'Japanese Yen (JPY)',
            'Jordanian Dinar (JOD)',
            'Kazakhstani Tenge (KZT)',
            'Kenyan Shilling (KES)',
            'Kuwaiti Dinar (KWD)',
            'Kyrgyzstani Som (KGS)',
            'Lao Kip (LAK)',
            'Lebanese Pound (LBP)',
            'Lesotho Loti (LSL)',
            'Libyan Dinar (LYD)',
            'Macanese Pataca (MOP)',
            'Macedonian Denar (MKD)',
            'Malagasy Ariary (MGA)',
            'Malawian Kwacha (MWK)',
            'Malaysian Ringgit (MYR)',
            'Mauritanian Ouguiya (MRU)',
            'Mauritian Rupee (MUR)',
            'Mexican Peso (MXN)',
            'Moldovan Leu (MDL)',
            'Mongolian Tugrik (MNT)',
            'Moroccan Dirham (MAD)',
            'Mozambican Metical (MZN)',
            'Namibian Dollar (NAD)',
            'New Taiwan Dollar (TWD)',
            'New Zealand Dollar (NZD)',
            'Nicaraguan Cordoba Oro (NIO)',
            'Nigerian Naira (NGN)',
            'Norwegian Krone (NOK)',
            'Omani Rial (OMR)',
            'Pakistani Rupee (PKR)',
            'Panamanian Balboa (PAB)',
            'Papua New Guinea Kina (PGK)',
            'Paraguay Guarani (PYG)',
            'Peruvian Nuevo Sol (PEN)',
            'Philippine Piso (PHP)',
            'Polish Złoty (PLN)',
            'Qatari Riyal (QAR)',
            'Romanian Leu (RON)',
            'Russian Ruble (RUB)',
            'Rwandan Franc (RWF)',
            'Salvadoran Colón (SVC)',
            'Saudi Riyal (SAR)',
            'Serbian Dinar (RSD)',
            'Seychellois Rupee (SCR)',
            'Sierra Leonean Leone (SLE)',
            'Singapore Dollar (SGD)',
            'South African Rand (ZAR)',
            'South Korean Won (KRW)',
            'South Sudanese Pound (SSP)',
            'Sri Lankan Rupee (LKR)',
            'Sudanese Pound (SDG)',
            'Swazi Lilangeni (SZL)',
            'Swedish Krona (SEK)',
            'Swiss Franc (CHF)',
            'Syrian Pound (SYP)',
            'Tanzanian Shilling (TZS)',
            'Thai Baht (THB)',
            'Trinidad and Tobago Dollar (TTD)',
            'Tunisian Dinar (TND)',
            'Turkish Lira (TRY)',
            'Turkmenistan New Manat (TMT)',
            'Ugandan Shilling (UGX)',
            'Ukrainian Hryvnia (UAH)',
            'United Arab Emirates Dirham (AED)',
            'Uruguayan Peso (UYU)',
            'Uzbekistan Som (UZS)',
            'Venezuelan Bolivar (VEF)',
            'Vietnamese Đồng (VND)',
            'West African CFA Franc (XOF)',
            'Yemeni Rial (YER)',
            'Zambian Kwacha (ZMW)',
            'Zimbabwean Dollar (ZWL)',
          ],
          target: 'employee_salary_currency',
        },
        {
          accuracy: 0.8,
          attributeDefinition:
            'If you use monthly base salary, the annual base salary is a calculation of monthly base salary*number of months paid, however this field is optional if you provide monthly base and number of months paid. Please indicate the gross annual base salary as of data effective date INCLUDING all salary sacrificed items. Annual base salary EXCLUDES any cash allowances, sur salary (specific to Francophone West Africa countries), superannuation and benefits.\n\nNorth America only: provide the "Annual base salary" only if you selected "Annual" as the incumbent\'s "Pay type".',
          attributeType: 'double',
          isRequired: true,
          sectionName: 'Employee',
          sampleValue: [
            '38209.6',
            '35380.8',
            '37606.4',
            '30076.8',
            '35380.8',
            '46301.3',
            '48825',
            '29473.6',
            '29494.4 ',
          ],
          target: 'annual_base_salary',
        },
        {
          accuracy: 0.8,
          attributeDefinition:
            'Annual amount of compensation for employees for working offshore.',
          attributeType: 'double',
          isRequired: false,
          sectionName: 'Employee',
          sampleValue: ['Blank'],
          target: 'guaranteed_offshore_allowance',
        },
        {
          accuracy: 0.8,
          attributeDefinition:
            'Annual guaranteed fixed cash allowance given to subsidize transportation to and from work. Includes fly-in/fly-out allowances, travel subsidies and travel payments. Does not include amounts provided as expense reimbursement. Does not include any benefit provided by company car policy (please do not confuse the transportation allowance with allowance in lieu of the company car or sum of car expenses covered by the organization) and is normally provided to all employees in the organization (if an organization has a transportation allowance policy) regardless of role or status (unlike car benefits).\n* For India, Pakistan, Sri Lanka & Bangladesh - this is referred to as "Conveyance Allowance".\n* For Japan - Transport Allowance is based on actual claim and therefore is not collected under this item.\n* For Colombia - this refers to Transportation Allowance in addition to what is required by law.',
          attributeType: 'double',
          isRequired: false,
          sectionName: 'Employee',
          sampleValue: [
            '120',
            '300',
            '348',
            '480',
            '360',
            '420',
            '552',
            '588',
            '600',
            '660',
            '672',
          ],
          target: 'annual_transportation_allowance',
        },
        {
          accuracy: 0.8,
          attributeDefinition:
            'Please choose the type of company car benefit applicable for each employee from the drop-down list. Please note that normally Company Car benefits are provided for employees with higher rank and seniority and should not be confused with subsidies paid for transportation to and from work (transportation allowance). As a Company Car Benefit Mercer recognizes both company car (the right to an actual vehicle which the employee may use on a permanent basis) and an allowance paid in lieu of a company car (instead of operating the actual vehicle).',
          attributeType: 'String',
          isRequired: false,
          sectionName: 'Employee',
          sampleValue: [
            'Not Eligible',
            'Company Car for Business Use Only',
            'Company Car for Business and Personal Use',
            'Cash Allowance in Lieu of Company Car',
            'Choice Between Company Car (Business and Personal Use) and Cash Allowance',
          ],
          target: 'company_car_benifit_type',
        },
        {
          accuracy: 0.8,
          attributeDefinition:
            'The amount paid per year in replacement of a company car for the employee. This is normally granted to employees with higher rank and seniority and should not be confused with subsidies paid for transportation to and from work (transportation allowance) which is normally provided to all employees in the organization.\n* For Australia, New Zealand, also include any amounts given for fuel, maintenance, or other expenses when provided via an allowance and not by a reimbursement.',
          attributeType: 'double',
          isRequired: false,
          sectionName: 'Employee',
          sampleValue: [
            '8640',
            '10800',
            '52000',
            '95040',
            '148911.36',
            '152296.32',
            '168575.52',
            '174960',
            '202197.48',
            '206369.28',
            '219364.56',
            '222549.12',
          ],
          target: 'annual_company_car_allowance',
        },
        {
          accuracy: 0.8,
          attributeDefinition:
            "Number of years after which employee's vehicle is replaced with a newer model.",
          attributeType: 'Numeric',
          isRequired: false,
          sectionName: 'Employee',
          sampleValue: ['3', '4', '5'],
          target: 'vehicle_replacement_term_years',
        },
        {
          accuracy: 0.8,
          attributeDefinition:
            'Please provide the purchase price of the car owned by the company.',
          attributeType: 'double',
          isRequired: false,
          sectionName: 'Employee',
          sampleValue: [
            '1040000',
            '957826',
            '850000',
            '987971.06',
            '990000',
            '1020000',
            '670000',
            '650000',
            '788000',
            '729000\n',
          ],
          target: 'vehicle_purchase_price',
        },
        {
          accuracy: 0.8,
          attributeDefinition:
            'The leasing/rent cost of the car offered by the organization to the employee which the organization incurs annually. The lease/rent cost includes typically amortization, maintenance, taxes, and car insurance costs. It does not include fuel cost.\nNote: This is applicable for employees who are eligible for company car.',
          attributeType: 'double',
          isRequired: false,
          sectionName: 'Employee',
          sampleValue: [
            '20200',
            '22100',
            '25700',
            '44900',
            '712269.36',
            '803736',
            '911544',
            '976212',
            '1138884',
            '4020000',
            '5758722',
          ],
          target: 'annual_lease_cost',
        },
        {
          accuracy: 0.8,
          attributeDefinition:
            'This indicates the consideration of row values in GST',
          attributeType: 'String',
          isRequired: false,
          sectionName: 'Employee',
          source: 'SYSTEM_EXCLUDE_EMPLOYEE',
          sampleValue: ['Yes', 'No'],
          target: 'system_exclude_employee',
        },
        {
          accuracy: 0.8,
          attributeDefinition: 'This is showing reasons of excluding employees',
          attributeType: 'String',
          isRequired: false,
          sectionName: 'Employee',
          sampleValue: [
            "[1] Employee's work location is blank.",
            '[1A] Base Salary is below country minimum wage.',
            '[1A] Monthly base salary or annual base salary are blank.',
            '[1B] Mercer benchmark code is blank.',
            "[1B] Mercer benchmark code is blank.,[1] Employee's work location is blank.",
            '[1B] Mercer benchmark code is blank.,[1A] Base Salary is below country minimum wage.',
            '[1B] Mercer benchmark code is blank.,[1A] Base Salary is below country minimum wage.,[6C] Other STIs (target) value outside of the typical range.',
            '[1B] Mercer benchmark code is blank.,[1A] Monthly base salary or annual base salary are blank.',
            '[1B] Mercer benchmark code is blank.,[1B] Mercer benchmark code is blank.',
            '[1B] Mercer benchmark code is blank.,[6C] Other STIs (target) value outside of the typical range.',
            '[1B] Mercer benchmark code is blank.,[6C] Sales incentive amount (actual) of the typical range.',
            '[1B] Mercer benchmark code is blank.,[6C] Short-Term Incentive (target) as percentage of base salary value outside of the range.',
            '[1B] Mercer benchmark code is blank.,[6C] Short-Term Incentive (variable bonus) amount (target) value outside of the range.,[6C] STI (bonus - actual) value outside of the typical range.',
            '[1B] Mercer benchmark code is blank.,[6L] Sales incentive amount (actual) of the typical range.',
            '[1B] Mercer benchmark code is blank.,[6L] Short-Term Incentive (target) as percentage of base salary value outside of the range.',
            '[1B] Mercer benchmark code is blank.,[6L] STI (bonus - actual) value outside of the typical range.',
            '[4A] Short-Term Incentive or Sales Incentive eligibility was blank.',
            "[4A] Short-Term Incentive or Sales Incentive eligibility was blank.,[1] Employee's work location is blank.\n",
          ],
          target: 'exclusion_reason',
        },
        {
          accuracy: 0.8,
          attributeDefinition:
            'This indicates the consideration of row values in GST',
          attributeType: 'String',
          isRequired: false,
          sectionName: 'Employee',
          source: 'CLIENT_EXCLUDE_EMPLOYEE',
          sampleValue: ['Yes', 'Client exclude employee (Mercer Use Only)'],
          target: 'client_exclude_employee',
        },
        {
          accuracy: 0.8,
          attributeDefinition: 'Job position identifier code in mercer library',
          attributeType: 'String',
          isRequired: true,
          sectionName: 'Employee',
          sampleValue: [
            'AFS.01.040.P30',
            'AFS.05.999.M30',
            'CRT.02.001.E10',
            'ENS.03.059.P30',
            'FIN.02.005.M40',
            'FIN.02.005.M50',
            'FIN.05.004.P30',
            'FIN.06.001.P30',
            'FIN.06.002.E10',
            'GMA.01.004.E24',
            'GMA.02.001.M50',
            'GMA.02.003.M40',
            'HRM.02.003.M40',
            'QLT.03.001.P40',
            'RET.01.002.M40',
            'RET.05.001.P40',
            'SCN.03.001.E20',
            'SMP.01.003.E24',
            'SMP.02.021.M40',
            'SMP.02.023.E20',
            'SMP.02.023.M40',
            'SMP.03.001.P30',
            'SMP.04.014.M40',
            'SMP.05.001.M40',
            'SMP.06.001.M50',
            'SMP.07.043.M40',
            'SMP.11.001.P50',
          ],
          target: 'mjl_position_code',
        },
        {
          accuracy: 0.8,
          attributeDefinition:
            'Job position identifier title in mercer library',
          attributeType: 'String',
          isRequired: true,
          sectionName: 'Employee',
          sampleValue: [
            'Accounting - Senior Professional (P3)',
            'Advertising & Marketing Communications - Senior Manager (M4)',
            'Budget Accounting - Senior Professional (P3)',
            'Business Development Strategy & Planning - Senior Manager (M4)',
            'Business Intelligence (BI) Data Analysis - Expert Professional (P5)',
            'Category Management - Senior Manager II (M5)',
            'Chief Operating Officer (COO)/Head of Operations - Regional (Multi-Country) Subsidiary (E2)',
            'Commercial/Pricing Strategy & Planning - Senior Manager (M4)',
            'Commercial/Pricing Strategy & Planning - Sub-function Executive 2 (E2)',
            'Compensation & Benefits - Senior Manager (M4)',
            'Executive Secretary/Executive Assistant - Entry Professional (P1)',
            'Field Training Instruction (Retail) - Specialist Professional (P4)',
            'Financial Planning & Analysis - Senior Manager (M4)',
            'Financial Planning & Analysis - Senior Manager II (M5)',
            'Financial Planning & Analysis - Specialist Professional (P4)',
            'Financial Reporting - Sub-function Executive 1 (E1)',
            'General Channel/Partner Sales - Senior Manager (M4)',
            'General Graphic Art/Design - Sub-function Executive 1 (E1)',
            'General Marketing - Senior Professional (P3)',
            'General Office Operations - Entry Professional (P1)',
            'General Office Operations - Senior Professional (P3)',
            'General Regulatory Affairs - Sub-function Executive 2 (E2)',
            'General Sales Operations/Administration - Expert Professional (P5)',
            'General Supply Chain Operations - Senior Manager (M4)',
            'General Supply Chain Operations - Specialist Professional (P4)',
            'Head of Finance/2nd Level Finance Executive - Senior Manager II (M5)',
            'Head of Marketing - Regional (Multi-Country) Subsidiary (E2)',
            'HR Business Partners - Senior Manager (M4)',
            'Innovation & Strategy - Senior Manager (M4)',
            'Long-Term Business Strategy & Planning - Senior Manager II (M5)',
            'Long-Term Business Strategy & Planning - Specialist Professional (P4)',
            'Manufacturing Quality Assurance - Senior Manager (M4)',
            'Manufacturing Quality Assurance - Specialist Professional (P4)',
            'Market Research & Analysis - Senior Manager (M4)',
            'Market Research & Analysis - Senior Manager II (M5)',
            'Multi-Store Management (Retail) - Senior Manager (M4)',
            'Other Property, Facilities & Asset Security - Manager (M3)',
            'Procurement - Sub-function Executive 2 (E2)',
            'Product Design Engineering - Senior Professional (P3)',
            'Product/Brand Management (P&L/Revenue Accountability) - Senior Manager (M4)',
          ],
          target: 'mjl_position_title',
        },
        {
          accuracy: 0.8,
          attributeDefinition:
            'The Library Specialty Flags are used in order to "flag" areas of specialization for some functions. This additional column enables to describe the incumbent matching more precisely - the consistent reporting of these flags will help to ensure the availability of granular compensation data which can provide a view on the compensation trends that may be particular to certain areas of specialization.',
          attributeType: 'String',
          isRequired: false,
          sectionName: 'Employee',
          sampleValue: [
            '< 4 Branches',
            '4 to 8 Branches',
            '9 to 12 Branches',
            '> 12 Branches',
            'Academic/Teaching and Learning',
            'External Engagement',
            'International',
            'Research',
            'Advancement',
            'Indigenous Education',
            'Acquisition Finance',
          ],
          target: 'mjl_speciality_flag',
        },
        {
          accuracy: 0.8,
          attributeDefinition:
            'It is the title that you give this job within your organization.',
          attributeType: 'String',
          isRequired: true,
          sectionName: 'Employee',
          sampleValue: [
            'Brand Excellence Coach, MENA & Turkey',
            'Brand Strategy Senior Manager Fanta',
            'Business Development Manager MENA',
            'Business Support Manager',
            'Customer Director - Modern Trade',
            'Customer Director (Strategic BIB Accounts) Middle East Franchise',
            'Designer MEA',
            'Director, Finance Intergration',
            'Director, Hydration, Sports, Coffee & Tea - Creative',
            'EMENA Senior Innovation Mgr for F&B',
            'Eurasia Middle East OU Commercial Finance',
            'Finance Analyst MENA and Turkey',
            'Franchise Operations Finance Director - MER',
            'Front Line Marketing Director - Middle East Region',
            'Front Line Portfolio Senior Manager - Middle East',
            'General Manager Emerging Markets',
            'Head of Growth',
            'HR Business Partner',
            'Human Insights Director',
            'Marketing Executive',
            "McDonald's Business Development Director-MEA (IA)",
            'New Ventures Director (Wabi & Daha Daha)',
            'Operations Excellence Coach, MENA & Turkey',
            'Operations Excellence Manager',
            'Quality & Food Safety Manager',
            'SAP Analyst',
            'Senior Brand Strategy Manager - Emerging Categories',
            'Senior Channel Manager Retail Middle East Franchise',
            'Senior Director, Customer-Large Retail & OP',
            'Senior Director, Sales and Marketing Equipment Procurement',
            'Senior Integrated Execution Manager, MER',
            'Senior Property Development Manager MEA',
            'Systems Economics and Competitive Landscape Director, Eurasia & Middle East',
            'TRM, Eurasia & ME OU',
            'VP of  Marketing - Eurasia & Middle East OU',
            'VP of Franchise Operations - Middle East',
          ],
          target: 'job_title',
        },
        {
          accuracy: 0.8,
          attributeDefinition:
            "Job code is your organization's internal job code that you use to identify the job within your organization/HRIS system.\nNote: this is NOT the employee personal identifier code/employee number.",
          attributeType: 'String',
          isRequired: false,
          sectionName: 'Employee',
          sampleValue: [
            '30017379',
            '30017418',
            '30017420',
            '30017482',
            '30017534',
            '30017575',
            '30017604',
            '30017655',
            '30017701',
            '30017705',
            '30017769',
            '30017784',
            '30017800',
            '30017973',
            '30018307',
            '30018512',
            '30020340',
            '30021205',
            '30021857',
            '30023750',
            '30025304',
          ],
          target: 'job_code',
        },
        {
          accuracy: 0.8,
          attributeDefinition:
            'If your organization has an internal leveling system, then this is the job level within the organization structure (e.g., the number of reporting positions below the head of the organization or a category such as manager or executive).\nIf your organization does not have an internal leveling system, leave this field blank.\nNote: This information is useful for data checking purposes, to link jobs to benefits policies and to organize survey reports according to level.',
          attributeType: 'String',
          isRequired: false,
          sectionName: 'Employee',
          sampleValue: [
            '1',
            '10',
            '11',
            '12',
            '13',
            '50000069',
            '50000071',
            '50000072',
            '50000106',
            '50000113',
            'Administrative/Technical',
            'ADMINISTRATIVO',
            'COORDENADOR',
            'Country Mngt',
            'Director',
            'DIRETOR PRESIDENTE',
            'ESPECIALISTA I',
            'ESPECIALISTA II',
            'Individual Contributor',
            'JG10',
            'JG11',
            'JG12',
            'JG13',
            'Junior Manager',
            'Level 1',
            'Level 10',
            'Level 11',
            'Level 12',
          ],
          target: 'job_level',
        },
        {
          accuracy: 0.8,
          attributeDefinition:
            "If your organization has an internal grading system, then this is the incumbent's job grade. Alternatively, if you use a job evaluation system, then this is the job grade you have allocated to the incumbent under that system.\nIf your organization does not have an internal grading system, leave this field blank.\nNote: This information is useful for data checking purposes, to link jobs to benefits policies and to organize survey reports according to grade.",
          attributeType: 'String',
          isRequired: false,
          sectionName: 'Employee',
          sampleValue: [
            '02',
            '03',
            '04',
            '05',
            '06',
            '07',
            '08',
            '2B',
            '3',
            '3A',
            '3B',
            '4',
            '4A',
            'A15P',
            'ASM',
            'ASM-SIC',
            'Associate Vice President',
            'Executive',
            'Level B',
            'Level C',
            'Level D',
            'Manager',
            'MDE',
            'Operatives',
            'S10',
            'S11',
            'Senior Vice President',
            'Vice President',
          ],
          target: 'job_grade',
        },
        {
          accuracy: 0.8,
          attributeDefinition:
            'Job title of the individual to whom the employee reports.',
          attributeType: 'String',
          isRequired: false,
          sectionName: 'Employee',
          sampleValue: [
            '2nd Shift Warehouse Shift Manager',
            'ABBP Operations Manager',
            'ACCESS ONLY : CLEANING SITE MANAGER',
            'ACCESS ONLY : CLEANING SUPERVISOR',
            'ACCESS ONLY : CLEANING TEAM LEADER',
            'ACCESS ONLY : WASTE SUPERVISOR',
            'ACCESS ONLY EMPLOYEE : IT',
            'Account Payable Team Lead',
            'ACCOUNTANT',
            'ACCOUNTANT ACCOUNTS PAYABLE',
            'ACCOUNTANT FINANCIAL MBEYA',
            'Accounting Manager, Cash & Investments',
            'Accounts Payable Accountant',
            'Accounts Payable Supervisor',
            'Accounts Receivable Team Leader',
            'Acting as QSE Manager',
            'ADES & Dairy General Manager',
            'Admin & Facility Manager',
            'Admin&EE Care Manager',
            'Administration and Services Supervisor',
            'Administrative Assistant',
            'Adult Emerging Brands, Nutrition & Experimentation Manager',
            'Advanced Analytics Solutions Director',
          ],
          target: 'supervisor_title',
        },
        {
          accuracy: 0.8,
          attributeDefinition:
            'Please provide only if you:\n1) are a licensed IPE user\n2) use evaluations established by a Mercer consultant.',
          attributeType: 'Numeric',
          isRequired: false,
          sectionName: 'Employee',
          sampleValue: [
            '40',
            '41',
            '42',
            '43',
            '44',
            '45',
            '46',
            '52',
            '57',
            '60',
            '65',
          ],
          target: 'ipe_position_class',
        },
        {
          accuracy: 0.8,
          attributeDefinition:
            'Only for employees with regional/global scope or executives of a business unit if this is different than for reporting company. For commercial Function Heads like Sales and Marketing, Sales, Marketing and Manufacturing, please provide the actual revenue for which the employee is responsible. For corporate Function Heads like Finance and Accounting, HR, IT, Medical etc., please provide the actual revenue of the company/business units/geography for which the employee is responsible.',
          attributeType: 'Numeric',
          isRequired: false,
          sectionName: 'Employee',
          sampleValue: ['Blank'],
          target: 'role_business_revenue',
        },
        {
          accuracy: 0.8,
          attributeDefinition:
            'Please indicate if the incumbent matched has responsibilities that encompass the following area:\n*Global: Worldwide\n*Multi-Regional: Two or more Regions, e.g. EMEA, Americas, Latin America and APAC, APAC and Middle East\n*Regional: Commonly accepted Geo-political area or substantial number of countries, e.g. Europe, Latin America, North America, APAC, Africa, Middle East.\n*Multi-Country: 3 to 8 countries within a region, e.g. Western or Eastern Europe, ASEAN, North Asia\n*In-Country: One country only, e.g. Australia, Bangladesh, China, India, Indonesia, Malaysia, Singapore, etc.\n*District: Geographically significant area within a country; typically used in large geographically diverse countries, e.g. Beijing, Shanghai, Guangdong, Chengdu-Chongqing, Mumbai, New Delhi, East Java, West Java, etc.',
          attributeType: 'String',
          isRequired: false,
          sectionName: 'Employee',
          sampleValue: [
            '10 - Global',
            '20 - Multi Regional (2-5 Regions)',
            '30 - Regional (e.g., Europe)',
            '50 - Multi Country (3-8 Countries)',
            '70 - In Country',
            '80 - District/Zone/State/Locality (Part of the Country)',
          ],
          target: 'role_geographic_scope',
        },
        {
          accuracy: 0.8,
          attributeDefinition:
            "Gender of the employee, reflecting the individual's identification as male, female, or another gender identity.",
          attributeType: 'String',
          isRequired: true,
          sectionName: 'Employee',
          sampleValue: ['Female', 'Male', 'Non-Binary'],
          target: 'Gender',
        },
        {
          accuracy: 0.8,
          attributeDefinition: 'Indication for excluding employees',
          attributeType: 'String',
          isRequired: true,
          sectionName: 'Employee',
          sampleValue: ['Yes'],
          target: 'exclude_flag',
        },
      ],
      sourceField: [
        'YOUR_EEID',
        'POS_CODE',
        'POS_TITLE',
        'EMP_010',
        'LIBSPEC_FLAG1',
        'YOUR_TITLE',
        'YOUR_CODE',
        'YOUR_LEVEL',
        'YOUR_GRADE',
        'YOUR_OTHER',
        'EMP_026',
        'POS_CLASS',
        'REV_RESP',
        'REGION_RESP',
        'EMP_037',
        'EMP_038',
        'EMP_044',
        'EMP_032',
        'EMP_047',
        'EMP_049',
        'EMP_124',
        'EMP_125',
        'EMP_128',
        'EMP_129',
        'EMP_172',
        'EMP_217',
        'EMP_221',
        'EMP_185',
        'EMP_233',
        'EMP_236',
        'EMP_238',
        'EMP_234',
        'EMP_449',
        'EMP_240',
        'EMP_244',
        'EMP_242',
        'EMP_250',
        'EMP_278',
        'EMP_280',
        'EMP_281',
        'EMP_282',
        'EMP_283',
        'EMP_284',
        'EMP_285',
        'EMP_379',
        'EMP_387',
        'EMP_388',
        'EMP_391',
        'EMP_394',
        'EMP_397',
        'EMP_392',
        'EMP_404',
        'SYSTEM_EXCLUDE_EMPLOYEE',
        'EXCLUDE_REASON',
        'CLIENT_EXCLUDE_EMPLOYEE',
      ],
    });
  }
}
